spring:
  liquibase:
    change-log: classpath:db/changelog/changeLog.prova.master.xml
    default-schema: public
  application:
    name: Prova
  datasource:
#    localHost:
    url: jdbc:postgresql://localhost:5432/prova

#    production:
#    url: jdbc:postgresql://172.106.0.55:10086/prova

    driver-class-name: org.postgresql.Driver
    password: unidule
    username: unidule
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL95alect
      ddl-auto: validate
    open-in-view: true
    show-sql: true

server:
  port: 8080

application:
  exigir-autenticacao: false
  exigir-autorizacao: false
