CREATE ROLE prova WITH
 NOLOGIN
 NOSUPERUSER
 NOCREATEDB
 NOCREATEROLE
 INHERIT
 NOREPLICATION
 CONNECTION LIMIT -1
 PASSWORD 'prova';

CREATE DATABASE prova
    WITH
    OWNER = prova
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;