spring:
  liquibase:
    change-log: classpath:db/changelog/changeLog.prova.master.xml
    default-schema: public
  application:
    name: unidule
  datasource:
    url: jdbc:postgresql://localhost:5432/unidulee
    driver-class-name: org.postgresql.Driver
    password: unidule
    username: unidule
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL95alect
      ddl-auto: validate
    open-in-view: true
    show-sql: true

server:
  port: 8080

application:
  exigir-autenticacao: false
  exigir-autorizacao: false
